import { firebaseClient } from './firebaseClient';

export class BlocklyInterceptor {
  private workspace: any = null;
  private roomId: string = 'default_room';

  constructor() {
    this.init();
    this.setupListeners();
  }

  private setupListeners() {
    firebaseClient.onBlockEvent((eventData: any) => {
      this.applyRemoteEvent(eventData);
    });
  }

  private init() {
    // Scratch loads Blockly asynchronously, so we poll for it
    const checkInterval = setInterval(() => {
      // @ts-ignore
      if (window.Blockly && window.Blockly.getMainWorkspace) {
        // @ts-ignore
        this.workspace = window.Blockly.getMainWorkspace();
        if (this.workspace) {
          clearInterval(checkInterval);
          this.hookEvents();
        }
      }
    }, 500);
  }

  private hookEvents() {
    console.log("Cloud Block: Attached to Blockly Workspace!");
    
    // Listen for room updates to change room ID
    const match = window.location.pathname.match(/\/projects\/(\d+)/);
    this.roomId = match ? match[1] : 'default_room';

    this.workspace.addChangeListener((event: any) => {
      // Ignore UI events (like clicking) that don't change logic
      if (event.type === 'ui') return;

      // Ignore events generated by our own sync
      if (event.recordUndo === false || event.isCloudBlockSync) return;

      console.log("Block changed:", event);
      
      // Emit to Firebase
      try {
        const eventJson = event.toJson();
        firebaseClient.emitBlockEvent(this.roomId, eventJson);
      } catch(e) {
        console.error("Cloud Block: Failed to serialize block event", e);
      }
    });
  }

  public applyRemoteEvent(eventData: any) {
    if (!this.workspace) return;
    
    // Handle workspace restoration from checkpoint
    if (eventData && eventData.type === 'restore_workspace') {
      console.log("Cloud Block: Restoring workspace from remote checkpoint");
      try {
        // @ts-ignore
        const xml = window.Blockly.Xml.textToDom(eventData.workspaceXml);
        // @ts-ignore
        window.Blockly.Events.disable();
        this.workspace.clear();
        // @ts-ignore
        window.Blockly.Xml.domToWorkspace(xml, this.workspace);
        // @ts-ignore
        window.Blockly.Events.enable();
      } catch (e) {
        console.error("Cloud Block: Failed to restore workspace from XML", e);
      }
      return;
    }

    try {
      // @ts-ignore
      const event = window.Blockly.Events.fromJson(eventData, this.workspace);
      event.isCloudBlockSync = true;
      
      // @ts-ignore
      window.Blockly.Events.disable();
      event.run(true);
      // @ts-ignore
      window.Blockly.Events.enable();
    } catch (e) {
      console.error("Cloud Block: Failed to run remote Blockly event", e);
    }
  }
}

// Initialize the interceptor when this script loads
new BlocklyInterceptor();

