import { socketClient } from './socketClient';

export class BlocklyInterceptor {
  private workspace: any = null;
  private roomId: string = 'default_room';

  constructor() {
    this.init();
    this.setupListeners();
  }

  private setupListeners() {
    socketClient.onBlockEvent((eventData: any) => {
      this.applyRemoteEvent(eventData);
    });
  }

  private init() {
    // Scratch loads Blockly asynchronously, so we poll for it
    const checkInterval = setInterval(() => {
      // @ts-ignore
      if (window.Blockly && window.Blockly.getMainWorkspace) {
        // @ts-ignore
        this.workspace = window.Blockly.getMainWorkspace();
        if (this.workspace) {
          clearInterval(checkInterval);
          this.hookEvents();
        }
      }
    }, 500);
  }

  private hookEvents() {
    console.log("Cloud Block: Attached to Blockly Workspace!");
    
    this.workspace.addChangeListener((event: any) => {
      // Ignore UI events (like clicking) that don't change logic
      if (event.type === 'ui') return;

      // Ignore events generated by our own sync
      if (event.recordUndo === false || event.isCloudBlockSync) return;

      console.log("Block changed:", event);
      
      // Emit to Socket.io via our socketClient
      try {
        const eventJson = event.toJson();
        socketClient.emitBlockEvent(this.roomId, eventJson);
      } catch(e) {
        console.error("Cloud Block: Failed to serialize block event", e);
      }
    });
  }

  public applyRemoteEvent(eventData: any) {
    if (!this.workspace) return;
    
    // @ts-ignore
    const event = window.Blockly.Events.fromJson(eventData, this.workspace);
    event.isCloudBlockSync = true;
    
    // @ts-ignore
    window.Blockly.Events.disable();
    event.run(true);
    // @ts-ignore
    window.Blockly.Events.enable();
  }
}

// Initialize the interceptor when this script loads
new BlocklyInterceptor();
